configure: support --with-lx

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,15 +1,18 @@
 #!/bin/sh
 
 config_mk="config.mk"
+with_xfce4_panel_applet=f
+with_gtktheme=f
+with_lx=f
 
 usage_message="Usage: ./configure
 Produce a config.mk file to be sourced by Makefile
 --prefix=<dir>
     Install architecture-independent files in \$prefix (e.g. --prefix=\$HOME')
 --with-xfce4-panel-applet
-    Include contrib/ package xfce4-panel-applet
 --with-gtktheme
-    Include contrib/ package gtktheme
+--with-lx
+    Include contrib/ packages
 --enable-asan
     Enable address sanitizer. Only use during development.
 -a, --all
@@ -21,35 +24,52 @@ add () {
 }
 
 check_required_bins () {
-	for bin
-	do
-		if ! type "$bin" >/dev/null 2>&1; then
-			printf '%b\n' "[FAIL] cannot find $bin"
-			exit 1
-		else
-			printf '%b\n' "[ OK ] $bin"
-		fi
-	done
+	if ! type "$*" >/dev/null 2>&1; then
+		printf '%b\n' "[FAIL] cannot find $*"
+		exit 1
+	else
+		printf '%b\n' "[ OK ] $*"
+	fi
 }
 
 check_required_libs () {
-	for lib
-	do
-		if ! pkg-config "$lib" >/dev/null 2>&1; then
-			printf '%b\n' "[FAIL] cannot find $lib"
-			exit 1
-		else
-			printf '%b\n' "[ OK ] $lib"
-		fi
-	done
+	if ! pkg-config "$*" >/dev/null 2>&1; then
+		printf '%b\n' "[FAIL] cannot find $*"
+		exit 1
+	else
+		printf '%b\n' "[ OK ] $*"
+	fi
+}
+
+add_modules () {
+	if [ "$with_xfce4_panel_applet" = "t" ]; then
+		check_required_libs "libxfce4panel-1.0"
+		add "CONTRIB_DIRS += xfce4-panel"
+	fi
+	if [ "$with_gtktheme" = "t" ]; then
+		add "CONTRIB_DIRS += gtktheme"
+	fi
+	if [ "$with_lx" = "t" ]; then
+		check_required_libs "libmenu-cache >= 1.1.0"
+		add "CONTRIB_DIRS += lx"
+	fi
+}
+
+check_core_dependencies () {
+	check_required_bins "pkg-config"
+	check_required_bins "xml2-config"
+	check_required_libs "x11"
+	check_required_libs "xrandr"
+	check_required_libs "cairo"
+	check_required_libs "pango"
+	check_required_libs "pangocairo"
+	check_required_libs "librsvg-2.0"
+	check_required_libs "glib-2.0"
 }
 
 main () {
 	rm -rf $config_mk
 	add "# Generated by configure script"
-
-	check_required_bins pkg-config xml2-config
-	check_required_libs x11 xrandr cairo pango pangocairo librsvg-2.0
 
 	for arg
 	do
@@ -59,15 +79,17 @@ main () {
 		--prefix)
 			add "prefix = $var" ;;
 		--with-xfce4-panel-applet)
-			check_required_libs libxfce4panel-1.0
-			add "CONTRIB_DIRS += xfce4-panel" ;;
+			with_xfce4_panel_applet=t ;;
 		--with-gtktheme)
-			add "CONTRIB_DIRS += gtktheme" ;;
+			with_gtktheme=t ;;
+		--with-lx)
+			with_lx=t ;;
 		--enable-asan)
 			add "ASAN=1" ;;
 		-a|--all)
-			add "CONTRIB_DIRS += xfce4-panel"
-			add "CONTRIB_DIRS += gtktheme"
+			with_xfce4_panel_applet=t
+			with_gtktheme=t
+			with_lx=t
 			;;
 		-h|--help)
 			printf '%b' "$usage_message"; exit 1 ;;
@@ -75,6 +97,8 @@ main () {
 			printf '%b\n' "warn: unknown option $opt" >&2 ;;
 		esac
 	done
+	check_core_dependencies
+	add_modules
 }
 
 main "$@"
